"""Read-only DB helpers for the dashboard plugin.

Self-contained on purpose: this module never imports from
``hermes_telemetry.dashboard`` and the standalone dashboard never imports
from here. The two surfaces stay fully decoupled — see
``tests/test_dashboard_plugin_isolation.py``.
"""

from __future__ import annotations

import os
import sqlite3
import threading
from datetime import datetime, timedelta, timezone
from pathlib import Path

_local = threading.local()


def db_path() -> Path:
    hermes_home = Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes"))
    return hermes_home / "telemetry" / "telemetry.db"


def conn() -> sqlite3.Connection:
    if not getattr(_local, "c", None):
        _local.c = sqlite3.connect(str(db_path()), isolation_level=None)
        _local.c.row_factory = sqlite3.Row
        _local.c.execute("PRAGMA busy_timeout=5000")
        _local.c.execute("PRAGMA query_only=ON")
    return _local.c


def rows(sql: str, params: tuple = ()) -> list[dict]:
    return [dict(r) for r in conn().execute(sql, params).fetchall()]


def one(sql: str, params: tuple = ()) -> dict:
    r = conn().execute(sql, params).fetchone()
    return dict(r) if r else {}


def coerce_window_hours(value) -> int:
    try:
        wh = int(value)
    except (TypeError, ValueError):
        return 24
    return max(0, wh)


def since_cutoff_iso(window_hours) -> str | None:
    wh = coerce_window_hours(window_hours)
    if wh <= 0:
        return None
    return (datetime.now(timezone.utc) - timedelta(hours=wh)).isoformat()


def since_clause(window_hours, col: str = "started_at") -> str:
    cutoff = since_cutoff_iso(window_hours)
    if cutoff is None:
        return "1=1"
    # cutoff is generated by us (no user input) — safe to inline.
    return f"{col} >= '{cutoff}'"
